### ISSUE TITLE
"Incompatible" error on KeePass 2.50

### ISSUE THREAD

**Issue by J-T-W** [Gugli/KeeLocker#1]
![2022-04-15 14_00_00-KeePass](https://user-images.githubusercontent.com/45880649/163631568-02571738-c8e2-4c04-b497-b292cd6628bf.jpg)

**Comment by Gugli** [comment]
It seems I've made a mistake when building the plugin.

I've updated the plgx file.
Can you try again please ?
https://github.com/Gugli/KeeLocker/releases/download/v1.2/KeeLocker.plgx

**Comment by J-T-W** [comment]
That seems to have fixed it.  Thanks
