### ISSUE TITLE
Not working or not using correctly

### ISSUE THREAD

**Issue by vertigo220** [Gugli/KeeLocker#2]
I don't know how exactly this is supposed to work since there's no documentation, but when I click "Fill drive GUID" it says "Unable to get GUID." I've tried entering the drive letter first, I've tried finding the GUID manually and entering that in there, but nothing makes this plugin work.

**Comment by Gugli** [comment]
Hello,

If you have a static drive (let's say a HDD bound to "D:") encrypted with bitlocker, you should  : 
- create a new entry, choose a title you want
- put the password for the drive in the entry usual password field
- Select "D:" as drive mountpoint in the KeeLocker tab

You can the either tick the checkbox "Unlock volume on opening" that will do so when the Database is opened (but that requires to close then open the DB). Or you can click "Unlock Volume" to test it right now.

If it is still not working : what flavor/version of windows are you using ?

**Comment by Gugli** [comment]
Note  : the Drive GUID feature is for more complex scenarios.
Eg : you use the same DB on multiple machines, along with a USB stick cyphered using BitLocker. The issue is that on the first machine, you USB stick mounts as "D:", but on another one, it mounts as "E:". In such cases, the "Drive Mountpoint" is not super useful, so instead of using it, you can use the "GUID", that should work in such scenarios.

**Comment by vertigo220** [comment]
Yeah, I understand the purpose of GUID, and that's why I'm trying to use it, but I have no idea how. It doesn't autofill it (which is what it looks like it would do when clicking the button) and entering it manually doesn't work.

**Comment by Gugli** [comment]
What flavor/version of windows are you using ?

**Comment by vertigo220** [comment]
Sorry. Win10x64 Pro 21H1 build 19043.1415

**Comment by Gugli** [comment]
I've been testing on my end, with a very similar OS (Windows 10 Pro x64 21H1 build 19043.1706 ). 
I created a USB stick :
- With "Used Space" (recommended) encryption.
- With the compatible mode OR with the new XTS-AES encryption. Both work.

When I choose the current drive mountpoint of a USB stick, and click "Fill drive GUID", it works. Unlocking also works.

The GUID should look something like : `\\?\Volume{123456ab-1234-1234-1234-123456789abc}\`

Do you see anything that could make a significant difference ?

**Comment by vertigo220** [comment]
Ok, that works, but the UI is very confusing and there are no instructions. The use of radio buttons suggests one *or* the other (which technically it is, but in this case you have to use one *then* the other, so while you're only using one in the end, you're still using both), so I didn't realize I had to select the drive in the top box then hit the button, the location of which directly under the bottom box makes it look like it's meant to be used with that box. I'd suggest a couple changes to make it more clear how to use it:

- Put the "Fill drive GUID" button under the "Drive mountpoint" box (or better yet, next to it, since that box only needs to be about a tenth of its current length) and put some space between those two and the "Drive GUID" box
- Add some brief instructions. For example, change "Use a GUID for removable drives that do not always mount on the same letter. Select a drive in "Drive mountpoint" dropdown and click "Fill drive GUID" button." You could also put this text in between the first dropdown and the button and second dropdown.

Unrelated, but, if possible, I'd also suggest having the drive dropdown show *all* drives, as it only shows A-H, and not all users may know they can simply type additional letters in.

**Comment by Gugli** [comment]
I've tried to improve the UI in v1.3 based on your suggestions.
I have also renamed the button to "Convert to GUID", and it is now disabled unless in "mountpoint" mode. I believe it's now clearer and does not need explicit instructions.

I'd love your feedback though.
Thanks

**Comment by vertigo220** [comment]
It looks better, at least from what I can recall. I should have looked again at the old layout before updating, but this does seem to make at least more sense. That said, I already know how it works now, so I can't look at it with fresh eyes, and while maybe not necessary, there are still a few things that could be done to make it easier:

- The main thing is I can still see users reading the note about the GUID and selecting that option directly, which then completely prevents them from being able to do it the proper way. They probably shouldn't be able to select it as a separate option, and it should be greyed out until they select a drive letter and click the button (I like the new label), at which point it gets filled in and un-greyed.
- I still think it should list all drive letters, not just A-H, and perhaps allow just the letter or the letter and colon (e.g. D or D: instead of D:\) and add the missing parts automatically. Not really necessary, but would just make it a bit more user-friendly and might help less technical people.
- While not necessary if the first point is done, if it's not, I still think a bit more explanation would be useful, and certainly couldn't hurt. Having three lines of text instead of one-and-a-half isn't going to be crowded or overwhelming but very well could make the difference between somebody figuring out immediately how to use it vs having to play with it a bit or even look online to figure it out. Again, I can't look at it with a fresh perspective anymore, but I would probably figure it out much easier with the new layout; however, many users are not tech-savvy, and something as minor as another sentence of instructions to help those users is, IMO, well worth it. Again, though, not as necessary if the first point is addressed.

**Comment by Gugli** [comment]
I think there are valid use-cases that are incompatible with the changes you are suggesting.

- People can obtain GUID from other sources. There are cases when you don't even have to mount your drive, but still want to unlock it (with VMs/cross-compilation tools/WSL). I don't think it's a good idea to forbid people from entering a GUID to improve UX : this would make it harder to use in those cases.
- The "Drive mountpoint" is a string (not just a drive letter). It's the very string I feed into the windows API. There are other syntaxes, like network shared storage, or drive mounted in a folder inside another drive. I don't want to temper with this string at all : there may be new syntaxes added in the future, or others I'm not aware of. Trying to be smart about this is bound to fail someday. The list of options is just here as a list of examples for this string, covering the most common cases.

That said : 
- I can add "..." at the end of the "Drive mountpoint" to make it more clear you can enter whatever you like
- I can replace the text with 
`Use a GUID for removable drives that do not always mount on the same letter. You can obtain the GUID of your drive by selecting its current "Drive mountpoint" then clicking on "Convert to GUID"`

Do you think this would make a significant improvement ?

**Comment by Gugli** [comment]
I have been trying some improvements.
![image](https://user-images.githubusercontent.com/2990145/211174537-37aa93ef-b495-4193-abe5-974c1cc88a00.png)

I will still have some ideas, but this is where I'm heading.

**Comment by Gugli** [comment]
And the window look like that when the combobox is collapsed
![image](https://user-images.githubusercontent.com/2990145/211174619-330d8c91-0da7-411c-a52a-31a76825984f.png)
