### ISSUE TITLE
it always unlocks automatically

### ISSUE THREAD

**Issue by blackwolfpt** [Gugli/KeeLocker#3]
I configured using the GUID and removed Unlock volume on opening but it continues to unlock automatically as soon as I enter DB.
This way it shouldn't unlock the drive without me running

![unlock](https://user-images.githubusercontent.com/9318597/185720687-79a793bd-a569-45e9-b0e7-ec27efd423ed.png)

**Comment by Gugli** [comment]
Should be fixed in v1.3.
