### ISSUE TITLE
Alternate methods for unlocking drives

### ISSUE THREAD

**Issue by vertigo220** [Gugli/KeeLocker#4]
For easily unlocking drives manually, a couple additional methods could be used by KeeLocker. Currently, there are three methods:

- Set it to unlock the drive when unlocking the DB
- Find and open the entry, switch to the KeeLocker tab, and use the "Unlock Volume Now" button
- Find the entry, copy the password, then open File Explorer and open the drive to bring up the BitLocker password box and paste the password into it

I propose the following:

- If possible, have KeePass/KeeLocker auto-detect the BitLocker password boxes and auto-fill them with the appropriate entry's password, or at least enable auto-fill via hotkeys
- Add menu entries to KeePass, one for individual entries to unlock specific drives (including if more than one entry is selected), and one in the (Tools?) menu to unlock all available drives. It might be preferable to open a dialog window to select the drives to unlock, starting with all locked drives checked so the user can uncheck any they don't want to unlock before continuing.
- If the first isn't possible, add an entry to Explorer's context menu to unlock the drive

**Comment by Gugli** [comment]
Interacting with the system Bitlocker box is hard. Due to the sensitive info it handles, Windows has several anti-tempering measures in place (ex : the UI closes as soon as it loses focus).
That's why I made the plugin in the first place : to workaround this uncooperative UI :)

I'm adding 3 menu entries : 
- one in the Tools menu to unlock all volumes
- one in the "Right click on entry" menu to unlock this one
- one in the "Right click on group" to unlock all the group
Do you think this would cover your use case ?

**Comment by vertigo220** [comment]
That sounds perfect. I didn't think the first option would work, so that's the next best thing and would make unlocking drives much easier.

**Comment by vertigo220** [comment]
@Gugli 

I've been using this plugin for a couple years now, and it's been great. I typically just use the Tools menu option to unlock all drives, but almost every time I find myself wishing this option was also located in the context menu when right-clicking the tray icon. This way, it would be as simple as right-clicking the icon and clicking that, vs now where I have to double-click to open KeePass, then click Tools, then the unlock option, then wait for it to unlock them (during which time KeePass is unresponsive, and this typically lasts for several seconds) then minimize KeePass. Not sure if you can add entries to that main context menu or if it's restricted to the app's own entries, but it would be very useful if it could be.
