### ISSUE TITLE
Unlock using recovery key instead of password

### ISSUE THREAD

**Issue by vertigo220** [Gugli/KeeLocker#5]
I have a few drives that don't have passwords, only identifiers and recovery keys, and the recovery key must be used to unlock them. I'm fairly certain this is due to the drive's being set up to unlock via TPM, and unfortunately passwords can't be added without disabling and reenabling BitLocker. KeeLocker doesn't work with recovery keys, only passwords, and it would be nice if it could either automatically tell if the "password" for a drive is a key and unlock it that way, or if there was a setting to tell it to use the password as a key.

**Comment by Gugli** [comment]
That should be done in the next version. I added a new setting in the keelocker tab to enable that.
