### ISSUE TITLE
Unlock drive when connected if KeePass database is open

### ISSUE THREAD

**Issue by vertigo220** [Gugli/KeeLocker#6]
If possible, it would be useful to have an option to unlock a drive automatically when it's connected, similar to how it unlocks drives automatically that are already connected when unlocking the database.

**Comment by Gugli** [comment]
This is probably out of scope for this plugin : it would need to have code running permanently in the background to check for new devices. And bitlocker is not reserved to Usb sticks, it can be network drives, etc...
I wouldn't even know where to start.

Sorry, I don't plan to do that for now.

**Comment by vertigo220** [comment]
Perfectly understandable. Assuming having it running in the background, which could be done with negligible resource usage, isn't a problem, perhaps a solution could be to simply poll for drives every x minutes and implement a shortcut or command so, when the shortcut keys are pressed or command is issued, it will do another poll to see what drive(s) is/are new since the last poll and unlock those drives.

**Comment by Gugli** [comment]
Should be fixed in 1.6.
 
https://github.com/Gugli/KeeLocker/commit/f8ade5138e216c86ce0575210906913b7bb76668
