### ISSUE TITLE
Trying to unlock a volume with the context menu has no effect.

### ISSUE THREAD

**Issue by steffen-heil** [Gugli/KeeLocker#8]
Trying to unlock a volume with the context menu has no effect.
Using "Unlock volume now" in the properties page, does work.

I tracked the problem to this line:
https://github.com/Gugli/KeeLocker/blob/main/KeeLocker/Plugin.cs#L257

In my case this is false, as I do not want to open my volumes when starting keepass.

**Comment by Gugli** [comment]
Should be fixed in the next release.
I'll try to do that tomorrow.

**Comment by Gugli** [comment]
Should be fixed in 1.5
