### ISSUE TITLE
Database opening very slow when unlocking volumes on open

### ISSUE THREAD

**Issue by vertigo220** [Gugli/KeeLocker#9]
When using KeeLocker to unlock drives upon opening the database, it slows the loading of the database as KeePass becomes unresponsive while the drives are being unlocked. Before using this option, the database would open within a couple seconds, whereas now it takes ~10+ seconds, with KeePass not being responsive and the database not loading until all the drives are unlocked. This feature has been tremendously useful, and I intend to keep using it even with this delay, but it would be nice if something could be done about it, whether optimizing it so it doesn't cause KeePass to essentially lock up or at least delaying the unlocking of the drives until the database is loaded.

**Comment by Gugli** [comment]
Upcoming 1.6 release may improve your situation. It's available in the releases page here (but not yet from keepass update screen, I'm testing it for a little while before).
